name: Deploy to GitHub Pages

# Trigger on pushes to the main branch
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository
    - uses: actions/checkout@v3

    # 2. (Optional) If you had a build step, you'd install & build here:
    #- name: Install dependencies
    #  run: npm ci
    #
    #- name: Build static assets
    #  run: npm run build

    # 3. Publish the contents of public/ to gh-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # This token is automatically provided by GitHub Actions
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Folder containing your static site
        publish_dir: public
        # Branch to push to; peaceiris/actions-gh-pages defaults to gh-pages,
        # so you can omit this if you like.
        publish_branch: gh-pages
