name: Deploy static site to GitHub Pages

on:
  push:
    branches:
    - master

permissions:
  pages: write
  id-token: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout your code
    - uses: actions/checkout@v4

    # 2. (Optional) build step here if you need one
    # - name: Install dependencies
    #   run: npm ci
    # - name: Build
    #   run: npm run build

    # 3. Upload your `public/` folder as the Pages artifact
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: public

  deploy:
    needs: build_and_upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    # 4. Deploy the artifact to GitHub Pages
    - uses: actions/deploy-pages@v1
