name: Deploy static site to GitHub Pages

on:
  push:
    branches:
    - master

permissions:
  pages: write
  id-token: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    # 1) Checkout your code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2) Debug: list the repository contents
    - name: List repository files
      run: ls -R .

    # 3) Create a deployment directory
    - name: Create deployment directory
      run: mkdir -p ./deploy

    # 4) Copy files to deployment directory
    - name: Copy HTML from docs folder
      run: cp -r ./docs/* ./deploy/

    # 5) Copy SignoTec script to root of deployment directory
    - name: Copy SignoTec script
      run: cp ./signotec/stpadserverscript.js ./deploy/

    # 6) Upload the deployment directory as the Pages artifact
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./deploy

  deploy:
    needs: build_and_upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    # 7) Deploy the artifact to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
